import = ["~/.config/alacritty/themes/themes/alabaster.toml"]

[env]
TERM = "xterm-256color"

[window]
decorations = "transparent"
opacity = 0.8
blur = true
startup_mode = "Maximized"
padding = { x = 24, y = 32 }

[font]
normal = { family = "Hasklug Nerd Font Mono", style = "Regular" }
size = 18
bold = { family = "Hasklug Nerd Font Mono", style = "Medium" }


[selection]
save_to_clipboard = true

[cursor]
style = { shape = "Block", blinking = "On" }
blink_interval = 320
thickness = 0.2
